# Imagem base com Python e Docker instalados
FROM python:3.9

# Instalação do pacote boto3
RUN pip install boto3

# Criação do diretório de trabalho
WORKDIR /app

# Copiar o código Python para o diretório de trabalho
COPY backup_script.py .

# Comando para executar o script Python
CMD ["python", "backup_script.py"]
